//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demonstration_exam_2024
{
    using System;
    using System.Collections.Generic;
    
    public partial class EquipmentAccess
    {
        public int access_id { get; set; }
        public int employee_id { get; set; }
        public string equipment_name { get; set; }
    
        public virtual Employee Employee { get; set; }
    }
}
