//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demonstration_exam_2024
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_PartnerSalesHistory
    {
        public int SaleId { get; set; }
        public Nullable<int> PartnerId { get; set; }
        public string ProductName { get; set; }
        public int Quantity { get; set; }
        public System.DateTime SaleDate { get; set; }
        public decimal SalePrice { get; set; }
        public Nullable<decimal> TotalAmount { get; set; }
    }
}
