//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demonstration_exam_2024
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_PartnerTotalSales
    {
        public int PartnerId { get; set; }
        public string CompanyName { get; set; }
        public Nullable<int> TotalSales { get; set; }
        public Nullable<int> TotalQuantity { get; set; }
        public Nullable<decimal> TotalAmount { get; set; }
    }
}
