//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demonstration_exam_2024
{
    using System;
    using System.Collections.Generic;
    
    public partial class Warehouse
    {
        public int warehouse_id { get; set; }
        public int material_id { get; set; }
        public int employee_id { get; set; }
        public System.DateTime operation_date { get; set; }
        public string operation_type { get; set; }
        public decimal quantity { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Material Material { get; set; }
    }
}
